export interface User {
    id: string;
    image: string;
    name: string;
    email: string;
    role: "customer" | "provider";
    createdAt: string;
    status: "active" | "pending" | "suspend" | "inactive";
}

export const demoUsers: User[] = [
    {
        id: "1",
        image: "/dashboard/user-management/user1.png",
        name: "John Doe",
        email: "john.doe@example.com",
        role: "customer",
        createdAt: "2024-01-15T10:30:00Z",
        status: "active",
    },
    {
        id: "2",
        image: "/dashboard/user-management/user2.png",
        name: "Sarah Wilson",
        email: "sarah.wilson@example.com",
        role: "provider",
        createdAt: "2024-02-20T14:45:00Z",
        status: "active",
    },
    {
        id: "3",
        image: "/dashboard/user-management/user3.png",
        name: "Mike Johnson",
        email: "mike.johnson@example.com",
        role: "customer",
        createdAt: "2024-03-10T09:15:00Z",
        status: "pending",
    },
    {
        id: "4",
        image: "/dashboard/user-management/user4.png",
        name: "Emily Brown",
        email: "emily.brown@example.com",
        role: "provider",
        createdAt: "2024-01-28T16:20:00Z",
        status: "suspend",
    },
    {
        id: "5",
        image: "/dashboard/user-management/user1.png",
        name: "David Lee",
        email: "david.lee@example.com",
        role: "customer",
        createdAt: "2024-02-05T11:00:00Z",
        status: "inactive",
    },
    {
        id: "6",
        image: "/dashboard/user-management/user2.png",
        name: "Lisa Taylor",
        email: "lisa.taylor@example.com",
        role: "provider",
        createdAt: "2024-03-25T13:45:00Z",
        status: "active",
    },
    {
        id: "7",
        image: "/dashboard/user-management/user3.png",
        name: "Robert Garcia",
        email: "robert.garcia@example.com",
        role: "customer",
        createdAt: "2024-01-08T08:30:00Z",
        status: "pending",
    },
    {
        id: "8",
        image: "/dashboard/user-management/user4.png",
        name: "Jennifer Martinez",
        email: "jennifer.martinez@example.com",
        role: "provider",
        createdAt: "2024-02-14T15:10:00Z",
        status: "suspend",
    },
    {
        id: "9",
        image: "/dashboard/user-management/user1.png",
        name: "James Anderson",
        email: "james.anderson@example.com",
        role: "customer",
        createdAt: "2024-01-22T12:00:00Z",
        status: "active",
    },
    {
        id: "10",
        image: "/dashboard/user-management/user2.png",
        name: "Maria Hernandez",
        email: "maria.hernandez@example.com",
        role: "provider",
        createdAt: "2024-03-05T16:45:00Z",
        status: "active",
    },
    {
        id: "11",
        image: "/dashboard/user-management/user3.png",
        name: "Michael Clark",
        email: "michael.clark@example.com",
        role: "customer",
        createdAt: "2024-02-18T09:30:00Z",
        status: "pending",
    },
    {
        id: "12",
        image: "/dashboard/user-management/user4.png",
        name: "Jessica Rodriguez",
        email: "jessica.rodriguez@example.com",
        role: "provider",
        createdAt: "2024-01-30T14:15:00Z",
        status: "suspend",
    },
    {
        id: "13",
        image: "/dashboard/user-management/user1.png",
        name: "Christopher Lewis",
        email: "christopher.lewis@example.com",
        role: "customer",
        createdAt: "2024-03-12T11:20:00Z",
        status: "inactive",
    },
    {
        id: "14",
        image: "/dashboard/user-management/user2.png",
        name: "Amanda Walker",
        email: "amanda.walker@example.com",
        role: "provider",
        createdAt: "2024-02-08T13:50:00Z",
        status: "active",
    },
    {
        id: "15",
        image: "/dashboard/user-management/user3.png",
        name: "Daniel Hall",
        email: "daniel.hall@example.com",
        role: "customer",
        createdAt: "2024-01-25T10:10:00Z",
        status: "pending",
    },
    {
        id: "16",
        image: "/dashboard/user-management/user4.png",
        name: "Ashley Allen",
        email: "ashley.allen@example.com",
        role: "provider",
        createdAt: "2024-03-18T15:30:00Z",
        status: "suspend",
    },
    {
        id: "17",
        image: "/dashboard/user-management/user1.png",
        name: "Matthew Young",
        email: "matthew.young@example.com",
        role: "customer",
        createdAt: "2024-02-12T08:45:00Z",
        status: "active",
    },
    {
        id: "18",
        image: "/dashboard/user-management/user2.png",
        name: "Stephanie King",
        email: "stephanie.king@example.com",
        role: "provider",
        createdAt: "2024-01-17T16:20:00Z",
        status: "active",
    },
    {
        id: "19",
        image: "/dashboard/user-management/user3.png",
        name: "Joshua Wright",
        email: "joshua.wright@example.com",
        role: "customer",
        createdAt: "2024-03-08T12:35:00Z",
        status: "pending",
    },
    {
        id: "20",
        image: "/dashboard/user-management/user4.png",
        name: "Nicole Scott",
        email: "nicole.scott@example.com",
        role: "provider",
        createdAt: "2024-02-25T14:00:00Z",
        status: "suspend",
    },
    {
        id: "21",
        image: "/dashboard/user-management/user1.png",
        name: "Kevin Green",
        email: "kevin.green@example.com",
        role: "customer",
        createdAt: "2024-01-19T09:15:00Z",
        status: "inactive",
    },
    {
        id: "22",
        image: "/dashboard/user-management/user2.png",
        name: "Samantha Adams",
        email: "samantha.adams@example.com",
        role: "provider",
        createdAt: "2024-03-15T17:25:00Z",
        status: "active",
    },
    {
        id: "23",
        image: "/dashboard/user-management/user3.png",
        name: "Brian Nelson",
        email: "brian.nelson@example.com",
        role: "customer",
        createdAt: "2024-02-03T11:40:00Z",
        status: "pending",
    },
    {
        id: "24",
        image: "/dashboard/user-management/user4.png",
        name: "Elizabeth Baker",
        email: "elizabeth.baker@example.com",
        role: "provider",
        createdAt: "2024-01-12T13:55:00Z",
        status: "suspend",
    },
    {
        id: "25",
        image: "/dashboard/user-management/user1.png",
        name: "Thomas Carter",
        email: "thomas.carter@example.com",
        role: "customer",
        createdAt: "2024-03-22T10:05:00Z",
        status: "active",
    },
    {
        id: "26",
        image: "/dashboard/user-management/user2.png",
        name: "Megan Roberts",
        email: "megan.roberts@example.com",
        role: "provider",
        createdAt: "2024-02-17T15:50:00Z",
        status: "active",
    },
    {
        id: "27",
        image: "/dashboard/user-management/user3.png",
        name: "Steven Phillips",
        email: "steven.phillips@example.com",
        role: "customer",
        createdAt: "2024-01-29T08:20:00Z",
        status: "pending",
    },
    {
        id: "28",
        image: "/dashboard/user-management/user4.png",
        name: "Rachel Evans",
        email: "rachel.evans@example.com",
        role: "provider",
        createdAt: "2024-03-05T14:35:00Z",
        status: "suspend",
    },
    {
        id: "29",
        image: "/dashboard/user-management/user1.png",
        name: "Joseph Turner",
        email: "joseph.turner@example.com",
        role: "customer",
        createdAt: "2024-02-22T12:10:00Z",
        status: "inactive",
    },
    {
        id: "30",
        image: "/dashboard/user-management/user2.png",
        name: "Lauren Parker",
        email: "lauren.parker@example.com",
        role: "provider",
        createdAt: "2024-01-14T16:45:00Z",
        status: "active",
    },
    {
        id: "31",
        image: "/dashboard/user-management/user3.png",
        name: "Charles Collins",
        email: "charles.collins@example.com",
        role: "customer",
        createdAt: "2024-03-19T09:25:00Z",
        status: "pending",
    },
    {
        id: "32",
        image: "/dashboard/user-management/user4.png",
        name: "Brittany Edwards",
        email: "brittany.edwards@example.com",
        role: "provider",
        createdAt: "2024-02-07T13:00:00Z",
        status: "suspend",
    },
    {
        id: "33",
        image: "/dashboard/user-management/user1.png",
        name: "Andrew Stewart",
        email: "andrew.stewart@example.com",
        role: "customer",
        createdAt: "2024-01-26T11:30:00Z",
        status: "active",
    },
    {
        id: "34",
        image: "/dashboard/user-management/user2.png",
        name: "Victoria Flores",
        email: "victoria.flores@example.com",
        role: "provider",
        createdAt: "2024-03-14T15:15:00Z",
        status: "active",
    },
    {
        id: "35",
        image: "/dashboard/user-management/user3.png",
        name: "Richard Morris",
        email: "richard.morris@example.com",
        role: "customer",
        createdAt: "2024-02-28T10:40:00Z",
        status: "pending",
    },
];
