export interface AuditLog {
    id: string;
    userName: string;
    role: string;
    action: string;
    module: string;
    dateTime: string;
    status: "Success" | "Failed" | "Warning";
    details: string;
    userImage: string;
}

export const auditLogs: AuditLog[] = [
    {
        id: "#LOG001",
        userName: "Sarah Johnson",
        role: "Administrator",
        action: "User Login",
        module: "Authentication",
        dateTime: "2024-01-15 14:23:45",
        status: "Success",
        details: "User logged in successfully",
        userImage: "/dashboard/user-management/user1.png",
    },
    {
        id: "#LOG002",
        userName: "Michael Chen",
        role: "Client",
        action: "Success Login",
        module: "Authentication",
        dateTime: "2024-01-15 14:18:32",
        status: "Success",
        details: "Client login successful",
        userImage: "/dashboard/user-management/user2.png",
    },
    {
        id: "#LOG003",
        userName: "David Rodriguez",
        role: "Provider",
        action: "Failed Login",
        module: "Authentication",
        dateTime: "2024-01-15 14:15:22",
        status: "Failed",
        details: "Invalid password attempt",
        userImage: "/dashboard/user-management/user3.png",
    },
    {
        id: "#LOG004",
        userName: "Emily Davis",
        role: "Administrator",
        action: "Wallet Off",
        module: "Settings",
        dateTime: "2024-01-15 14:12:15",
        status: "Success",
        details: "Wallet feature disabled",
        userImage: "/dashboard/user-management/user4.png",
    },
    {
        id: "#LOG005",
        userName: "James Wilson",
        role: "Client",
        action: "Review",
        module: "Payment successful",
        dateTime: "2024-01-15 14:08:33",
        status: "Warning",
        details: "Payment review required",
        userImage: "/dashboard/user-management/user1.png",
    },
    {
        id: "#LOG006",
        userName: "Lisa Anderson",
        role: "Provider",
        action: "Forgot Password",
        module: "Authentication",
        dateTime: "2024-01-15 14:05:18",
        status: "Success",
        details: "Password reset requested",
        userImage: "/dashboard/user-management/user2.png",
    },
    {
        id: "#LOG007",
        userName: "Robert Brown",
        role: "Administrator",
        action: "User Registration",
        module: "Authentication",
        dateTime: "2024-01-15 13:58:12",
        status: "Success",
        details: "New user registered",
        userImage: "/dashboard/user-management/user3.png",
    },
    {
        id: "#LOG008",
        userName: "Maria Garcia",
        role: "Provider",
        action: "Profile Update",
        module: "Profile",
        dateTime: "2024-01-15 13:45:33",
        status: "Success",
        details: "Profile information updated",
        userImage: "/dashboard/user-management/user4.png",
    },
    {
        id: "#LOG009",
        userName: "Thomas Lee",
        role: "Client",
        action: "Payment Processing",
        module: "Payment",
        dateTime: "2024-01-15 13:32:21",
        status: "Failed",
        details: "Payment processing failed - insufficient funds",
        userImage: "/dashboard/user-management/user1.png",
    },
    {
        id: "#LOG010",
        userName: "Jennifer Martinez",
        role: "Administrator",
        action: "System Settings Update",
        module: "Settings",
        dateTime: "2024-01-15 13:25:44",
        status: "Success",
        details: "System configuration updated",
        userImage: "/dashboard/user-management/user2.png",
    },
    {
        id: "#LOG011",
        userName: "Kevin Smith",
        role: "Provider",
        action: "Service Creation",
        module: "Services",
        dateTime: "2024-01-15 13:18:09",
        status: "Success",
        details: "New service created successfully",
        userImage: "/dashboard/user-management/user3.png",
    },
    {
        id: "#LOG012",
        userName: "Amanda White",
        role: "Client",
        action: "Booking Cancellation",
        module: "Bookings",
        dateTime: "2024-01-15 13:12:37",
        status: "Warning",
        details: "Booking cancelled - refund processed",
        userImage: "/dashboard/user-management/user4.png",
    },
    {
        id: "#LOG013",
        userName: "Daniel Clark",
        role: "Administrator",
        action: "User Permission Change",
        module: "User Management",
        dateTime: "2024-01-15 13:05:28",
        status: "Success",
        details: "User permissions updated",
        userImage: "/dashboard/user-management/user1.png",
    },
    {
        id: "#LOG014",
        userName: "Sophia Taylor",
        role: "Provider",
        action: "Availability Update",
        module: "Schedule",
        dateTime: "2024-01-15 12:58:14",
        status: "Success",
        details: "Working hours updated",
        userImage: "/dashboard/user-management/user2.png",
    },
    {
        id: "#LOG015",
        userName: "Christopher Harris",
        role: "Client",
        action: "Review Submission",
        module: "Reviews",
        dateTime: "2024-01-15 12:45:52",
        status: "Success",
        details: "Service review submitted",
        userImage: "/dashboard/user-management/user3.png",
    },
    {
        id: "#LOG016",
        userName: "Michelle King",
        role: "Administrator",
        action: "Database Backup",
        module: "System",
        dateTime: "2024-01-15 12:38:27",
        status: "Success",
        details: "Scheduled database backup completed",
        userImage: "/dashboard/user-management/user4.png",
    },
    {
        id: "#LOG017",
        userName: "Andrew Scott",
        role: "Provider",
        action: "Withdrawal Request",
        module: "Wallet",
        dateTime: "2024-01-15 12:25:19",
        status: "Failed",
        details: "Withdrawal request failed - minimum amount not met",
        userImage: "/dashboard/user-management/user1.png",
    },
    {
        id: "#LOG018",
        userName: "Jessica Adams",
        role: "Client",
        action: "Password Change",
        module: "Security",
        dateTime: "2024-01-15 12:18:43",
        status: "Success",
        details: "Password updated successfully",
        userImage: "/dashboard/user-management/user2.png",
    },
    {
        id: "#LOG019",
        userName: "Matthew Evans",
        role: "Administrator",
        action: "Email Template Update",
        module: "Communication",
        dateTime: "2024-01-15 12:12:08",
        status: "Success",
        details: "Email templates modified",
        userImage: "/dashboard/user-management/user3.png",
    },
    {
        id: "#LOG020",
        userName: "Elizabeth Green",
        role: "Provider",
        action: "Document Upload",
        module: "Documents",
        dateTime: "2024-01-15 12:05:34",
        status: "Warning",
        details: "Document uploaded - pending verification",
        userImage: "/dashboard/user-management/user4.png",
    },
];
